on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          access_token: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
          languages: 'ja'