on: [push]

jobs:
  crowdin-translation-progress:
    runs-on: ubuntu-latest
    name: crowdin translation progress
    steps:
      - name: crowdin translation progress
        uses: hangwoo/crowdin-translation-progress@v1.0.0
        with:
          access_token: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
          languages: 'ja'
          project_id: '392841'